/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: '前言',
	  items: ['README', 'preface_guowenzhe', 'preface', 'preface_labview'],
    },
	{
      type: 'category',
      label: '正文',
	  items: [
	    {
          type: 'category',
		  label: 'LabVIEW 入门',
          link: {
            type: 'doc',
            id: 'ramp_up',
          },
          items: [ 
		    'ramp_up_install', 
			'ramp_up_hello_world', 
			'ramp_up_how_to_learn', 
			'ramp_up_complex_vis',
			'ramp_up_dev_environment'
		  ],
        },
	  ],
    },
  ],

};

module.exports = sidebars;
